### ISSUE TITLE
Lookbehind Regex breaking for Safari users

### ISSUE THREAD

**Issue by KevinMulhern** [decanTyme/chartjs-plugin-tailwindcss-colors#36]
Hi, thanks for this great tool. It's been _super_ useful and a massive timesaver, I really appreciate you making this available. 

Some of our users are reporting that our JavaScript is not working in Safari. They are getting this error in the console: `SyntaxError: Invalid regular expression: invalid group specifier name`

I've tracked it down to this https://github.com/decanTyme/chartjs-plugin-tailwindcss-colors/blob/cec656af2e8d540074d7222192de224bf8513fb5/src/utils.ts#L29 

Versions of Safari prior to 16.4 [don't support lookbehind](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group) JS regexes and thats causing the rest of the JS to flake out.

Is there something else that could be used to achieve the same thing in that regex?

**Comment by decanTyme** [comment]
Hello, thanks for reporting. Glad the project has been useful!

In this case, we can just use `?:` since we just check for valid values. IIRC tho, I was looking to replace that util with just regex exec (we need the matched values anyway), so this is a good catch and I'll keep it in mind.

P.S. Haven't looked for improvements for this project for a while now since it's working for me w/o issues. Tho it does say in the exact function where that snippet is found that there *should* be more room for it 😆

**Comment by decanTyme** [comment]
Fix has been released in [0.2.3](https://github.com/decanTyme/chartjs-plugin-tailwindcss-colors/releases/tag/v0.2.3) 🥳

You can try it out now and let me know if you have any other issues.

**Comment by KevinMulhern** [comment]
Thanks so much @decanTyme 🎉 

It looks like there is one more https://github.com/decanTyme/chartjs-plugin-tailwindcss-colors/blob/83e15e6f688d5233a88c7b9090bf6c3441cd97c8/src/utils.ts#L6

With that changed to `?:` everything starts working as expected on my end.

Sorry for the trouble, I should have done a better job of looking for any other instances when writing up the initial report!

**Comment by decanTyme** [comment]
No worries. I didn't really have any significant safari userbase where I use this plugin, so I didn't catch it earlier in the project either. My bad and thanks again for reporting!

To be honest, when I wrote this it was when regex stuff was new to me, so I had no idea and in fact just now realized that I might not even need the lookbehind in all cases where we're only checking, since lookahead does the trick fine. 

> It looks like there is one more
> 
> https://github.com/decanTyme/chartjs-plugin-tailwindcss-colors/blob/83e15e6f688d5233a88c7b9090bf6c3441cd97c8/src/utils.ts#L6

Negative lookahead appears to be [well supported](https://caniuse.com/mdn-javascript_regular_expressions_lookahead_assertion) so that might be what we're looking for in that case.

Anyway, the reason I needed both lookbehinds was because of some edge cases where it might crash if it tries to parse invalid values. Since I just copied the initial color parser over from the Tailwind repo, I added in the regex protections myself. I might need to rewrite it altogether so the checking/parsing is simple and straightforward.

**Comment by decanTyme** [comment]
Alright, a new fix has been [released](https://github.com/decanTyme/chartjs-plugin-tailwindcss-colors/releases/tag/v0.2.4) 🥳

Just to be extra sure, I tested it this time via [BrowserStack](https://live.browserstack.com/dashboard#os=OS+X&os_version=Monterey&browser=Safari&browser_version=15.6&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2F66c31b550e2299dd17c88308--amazing-crisp-c728d7.netlify.app%2F&speed=1) (Safari 15.6, Monterey), and it appears that there are no errors anymore.

Just a heads up tho, if npm still permits, I will probably unpublish v0.2.3 just because it's redundant and nobody should be installing it anyway.

**Comment by KevinMulhern** [comment]
Great stuff, thanks @decanTyme all working on my end and got confirmation it's working for the affected users too 🥳
